ALTER TYPE "SalesRegion" ADD VALUE IF NOT EXISTS 'NORTH_1';
ALTER TYPE "SalesRegion" ADD VALUE IF NOT EXISTS 'NORTH_2';
ALTER TYPE "SalesRegion" ADD VALUE IF NOT EXISTS 'SOUTH_1';
ALTER TYPE "SalesRegion" ADD VALUE IF NOT EXISTS 'SOUTH_2';
ALTER TYPE "SalesRegion" ADD VALUE IF NOT EXISTS 'WEST_1';
ALTER TYPE "SalesRegion" ADD VALUE IF NOT EXISTS 'WEST_2';
ALTER TYPE "SalesRegion" ADD VALUE IF NOT EXISTS 'ROM';
ALTER TYPE "SalesRegion" ADD VALUE IF NOT EXISTS 'CENTRAL';