import type { AdminListInput } from "@/server/admin/admin.types";
import type { SalesRegion, UserRole, UserStatus } from "@prisma/client";

export type AdminStaffListInput = AdminListInput & { role?: "NSM" };
export type AdminStaffRole = Extract<UserRole, "STAFF" | "RSM" | "ASM" | "NSM">;
export type AdminCreateUserRole = Extract<UserRole, "NSM" | "RSM" | "ASM" | "STAFF">;

export type AdminStaffRecord = {
  id: bigint;
  displayName: string;
  designation: string | null;
  location: string | null;
  mobileNo: string | null;
  alternateNo: string | null;
  permanentAddress: string | null;
  localAddress: string | null;
  gender: string | null;
  dob: Date | null;
  nationality: string | null;
  maritalStatus: string | null;
  qualification: string | null;
  emergencyContactNo1: string | null;
  emergencyContactNo2: string | null;
  staffRoleType: string | null;
  salesRegion: SalesRegion | null;
  parentRsmId: bigint | null;
  parentAsmId: bigint | null;
  assignedStates: string[];
  assignedCities: string[];
  reportingManagerId: bigint | null;
  parentRsm?: { id: bigint; displayName: string; user: { id: bigint; email: string } } | null;
  parentAsm?: { id: bigint; displayName: string; user: { id: bigint; email: string } } | null;
  reportingManager?: { id: bigint; displayName: string; user: { id: bigint; email: string } } | null;
  user: { id: bigint; email: string; username: string | null; status: string; role: UserRole };
};
export type CreateAdminStaffInput = {
  name: string;
  email: string;
  password: string;
  role: AdminCreateUserRole;
  designation?: string;
  location?: string;
  mobileNo?: string;
  alternateNo?: string;
  permanentAddress?: string;
  localAddress?: string;
  gender?: string;
  dob?: Date;
  nationality?: string;
  maritalStatus?: string;
  qualification?: string;
  emergencyContactNo1?: string;
  emergencyContactNo2?: string;
  staffRoleType?: string;
  salesRegion?: SalesRegion;
  parentRsmId?: string;
  parentAsmId?: string;
  assignedStates?: string[];
  assignedCities?: string[];
  reportingManagerId?: string;
  status?: UserStatus;
};

export type UpdateAdminStaffInput = {
  name?: string;
  email?: string;
  role?: AdminStaffRole;
  designation?: string;
  location?: string;
  mobileNo?: string;
  alternateNo?: string;
  permanentAddress?: string;
  localAddress?: string;
  gender?: string;
  dob?: Date;
  nationality?: string;
  maritalStatus?: string;
  qualification?: string;
  emergencyContactNo1?: string;
  emergencyContactNo2?: string;
  staffRoleType?: string;
  salesRegion?: SalesRegion;
  parentRsmId?: string;
  parentAsmId?: string;
  assignedStates?: string[];
  assignedCities?: string[];
  reportingManagerId?: string;
  status?: UserStatus;
};
