import type { Metadata } from "next";
// import Footer from "../../components/Footer";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

// import Footer from "@/components/footer";
// import Header from "@/components/Header";
// import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <div
      className="antialiased">
      <div className="sticky top-0 z-50">
        <Header />
      </div>
      {children}
      <Footer />
    </div>
  );
}
